<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SGESGNG" failures="8" tests="8" name="Test" time="56.671" errors="0" timestamp="2024-10-10T23:13:41 IST">
  <testcase classname="pageobjectmodeljat21.TC002_SignupTest" name="SignupTest" time="3.395">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Sign up successful.&amp;gt; but was:&amp;lt;Please fill out Username and Password..&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Sign up successful.> but was:<Please fill out Username and Password..>
at pageobjectmodeljat21.TC002_SignupTest.SignupTest(TC002_SignupTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- SignupTest -->
  <testcase classname="pageobjectmodeljat21.TC002_SignupTest" name="SignupTest" time="2.856">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;This user already exist.&amp;gt; but was:&amp;lt;Please fill out Username and Password..&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<This user already exist.> but was:<Please fill out Username and Password..>
at pageobjectmodeljat21.TC002_SignupTest.SignupTest(TC002_SignupTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- SignupTest -->
  <testcase classname="pageobjectmodeljat21.TC002_SignupTest" name="SignupTest" time="2.799">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;This user already exist.&amp;gt; but was:&amp;lt;Please fill out Username and Password..&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<This user already exist.> but was:<Please fill out Username and Password..>
at pageobjectmodeljat21.TC002_SignupTest.SignupTest(TC002_SignupTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- SignupTest -->
  <testcase classname="pageobjectmodeljat21.TC002_SignupTest" name="SignupTest" time="2.744">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Please fill out Username and Password.&amp;gt; but was:&amp;lt;Please fill out Username and Password..&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Please fill out Username and Password.> but was:<Please fill out Username and Password..>
at pageobjectmodeljat21.TC002_SignupTest.SignupTest(TC002_SignupTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- SignupTest -->
  <testcase classname="pageobjectmodeljat21.TC001_LoginTest" name="LoginTest" time="2.869">
    <failure type="org.openqa.selenium.NoAlertPresentException" message="no such alert
  (Session info: chrome=128.0.6613.138)
Build info: version: &amp;apos;4.24.0&amp;apos;, revision: &amp;apos;748ffc9bc3&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.10&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [358f08a40319daaf7439116b89b12759, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.138, chrome: {chromedriverVersion: 128.0.6613.137 (fe621c5aa2d..., userDataDir: C:\Users\Admin\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:59372}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59372/devtoo..., se:cdpVersion: 128.0.6613.138, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 358f08a40319daaf7439116b89b12759">
      <![CDATA[org.openqa.selenium.NoAlertPresentException: no such alert
  (Session info: chrome=128.0.6613.138)
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [358f08a40319daaf7439116b89b12759, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.138, chrome: {chromedriverVersion: 128.0.6613.137 (fe621c5aa2d..., userDataDir: C:\Users\Admin\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:59372}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59372/devtoo..., se:cdpVersion: 128.0.6613.138, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 358f08a40319daaf7439116b89b12759
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1190)
at pageobjectmodeljat21.TC001_LoginTest.LoginTest(TC001_LoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="pageobjectmodeljat21.TC001_LoginTest" name="LoginTest" time="2.895">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Wrong password.&amp;gt; but was:&amp;lt;Wrong password&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Wrong password.> but was:<Wrong password>
at pageobjectmodeljat21.TC001_LoginTest.LoginTest(TC001_LoginTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="pageobjectmodeljat21.TC001_LoginTest" name="LoginTest" time="2.796">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Wrong password.&amp;gt; but was:&amp;lt;User does not exist.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Wrong password.> but was:<User does not exist.>
at pageobjectmodeljat21.TC001_LoginTest.LoginTest(TC001_LoginTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="pageobjectmodeljat21.TC001_LoginTest" name="LoginTest" time="2.801">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Wrong password.&amp;gt; but was:&amp;lt;User does not exist.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Wrong password.> but was:<User does not exist.>
at pageobjectmodeljat21.TC001_LoginTest.LoginTest(TC001_LoginTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- Test -->
